In [1]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [2]:
import os
os.chdir("C:\Program Files\AIML PG")

In [5]:
data = pd.read_csv("german_credit.csv")
data.head(5)

default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex      ...       present_res_since  \
0                        male : single      ...                       4   
1  female : divorced/separated/married      ...                       2   
2                        male : single      ...                       3   
3                        male : single      ...                       4   
4                        male : single      ...                       4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

In [0]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable

(1000, 21)
Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')


default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex      ...       present_res_since  \
0                        male : single      ...                       4   
1  female : divorced/separated/married      ...                       2   
2                        male : single      ...                       3   
3                        male : single      ...                       4   
4                        male : single      ...                       4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [9]:
from sklearn.model_selection import train_test_split
train_data,test_data = train_test_split(data,test_size=0.5,shuffle=True,stratify=data['default'])
print(train_data.shape,test_data.shape)
y_train_data = train_data['default']
x_train_data = train_data.drop('default',inplace=False,axis=1)

(500, 21) (500, 21)


In [0]:
# Lets build a Ensemble model but need to modify the dataset first


### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [10]:
# Print Shape of model data
x_train_data_transform=pd.get_dummies(x_train_data)
x_train_data_transform.shape

(500, 61)

### Check for highly correlated variables but don't required any treatment for this use case

In [17]:
x_train_data_transform.corr()

duration_in_month  \
duration_in_month                                            1.000000   
credit_amount                                                0.617543   
installment_as_income_perc                                   0.063164   
present_res_since                                            0.009331   
age                                                         -0.052585   
credits_this_bank                                            0.002803   
people_under_maintenance                                    -0.038010   
account_check_status_0 <= ... < 200 DM                       0.085209   
account_check_status_< 0 DM                                  0.021269   
account_check_status_>= 200 DM / salary assignm...          -0.040307   
account_check_status_no checking account                    -0.074498   
credit_history_all credits at this bank paid ba...           0.017177   
credit_history_critical account/ other credits ...          -0.073765   
credit_history_delay in paying off in the past               0.104324   
credit_history_existing credits paid back duly ...          -0.027007   
credit_history_no credits taken/ all credits pa...           0.071287   
purpose_(vacation - does not exist?)                        -0.058632   
purpose_business                                             0.148385   
purpose_car (new)                                           -0.093410   
purpose_car (used)                                           0.167461   
purpose_domestic appliances                                 -0.071207   
purpose_education                                            0.011012   
purpose_furniture/equipment                                  0.150921   
purpose_radio/television                                    -0.041076   
purpose_repairs                                             -0.066949   
purpose_retraining                                          -0.089884   
savings_.. >= 1000 DM                                       -0.040241   
savings_... < 100 DM                                        -0.015262   
savings_100 <= ... < 500 DM                                  0.046985   
savings_500 <= ... < 1000 DM                                -0.095868   
...                                                               ...   
present_emp_since_.. >= 7 years                              0.015114   
present_emp_since_... < 1 year                              -0.066239   
present_emp_since_1 <= ... < 4 years                        -0.065174   
present_emp_since_4 <= ... < 7 years                         0.103371   
present_emp_since_unemployed                                 0.050358   
personal_status_sex_female : divorced/separated...          -0.091378   
personal_status_sex_male : divorced/separated                0.026956   
personal_status_sex_male : married/widowed                  -0.062749   
personal_status_sex_male : single                            0.109897   
other_debtors_co-applicant                                   0.031116   
other_debtors_guarantor                                     -0.053096   
other_debtors_none                                           0.020402   
property_if not A121 : building society savings...          -0.051158   
property_if not A121/A122 : car or other, not i...           0.108886   
property_real estate                                        -0.200259   
property_unknown / no property                               0.174188   
other_installment_plans_bank                                 0.049115   
other_installment_plans_none                                -0.078885   
other_installment_plans_stores                               0.066496   
housing_for free                                             0.173611   
housing_own                                                 -0.062820   
housing_rent                                                -0.063938   
job_management/ self-employed/ highly qualified...           0.104656   
job_skilled employee / official      

### Drop the original variables which are converted to dummy

In [ ]:
#The original variable does not exist once they get converted to dummies

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x_train_data_transform,y_train_data,test_size=0.3)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(350, 61) (150, 61) (350,) (150,)


### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [23]:
from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)

In [26]:
random_forest_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
                       oob_score=False, random_state=9999, verbose=0,
                       warm_start=False)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_predicted = random_forest_model.predict(x_test)
print("confusion matrix")
print(confusion_matrix(y_test,y_predicted))
print('')
print("accuracy score")
print(accuracy_score(y_test,y_predicted))

confusion matrix
[[96  6]
 [32 16]]

accuracy score
0.7466666666666667


### Q6 Show the list of the features importance( 1 Marks)

In [29]:
importances=random_forest_model.feature_importances_
importances

array([0.06828229, 0.09324993, 0.03017182, 0.03416667, 0.0836399 ,
       0.01905874, 0.01307898, 0.02094507, 0.0311626 , 0.01267288,
       0.04565884, 0.00573098, 0.01836219, 0.00762597, 0.01670746,
       0.00917206, 0.00718604, 0.01036069, 0.01399231, 0.00971599,
       0.01855711, 0.00410343, 0.00242291, 0.01373824, 0.00105743,
       0.00018029, 0.00746292, 0.02022031, 0.00672952, 0.00335703,
       0.01561261, 0.01429631, 0.01387361, 0.01721391, 0.01328803,
       0.00876109, 0.01796449, 0.00779374, 0.00801731, 0.01896364,
       0.00592451, 0.00753956, 0.00877588, 0.0155526 , 0.01543925,
       0.01475462, 0.01094218, 0.01843004, 0.0187291 , 0.00679518,
       0.0085655 , 0.02118279, 0.01258128, 0.01226817, 0.01419888,
       0.00088702, 0.01056306, 0.01269665, 0.0129931 , 0.00307609,
       0.00354922])

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [30]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [31]:
# Use below values
num_folds = 10
seed = 77

In [0]:
#Validate the Random Forest model build above using k fold

In [50]:
k_fold=KFold(n_splits=num_folds,random_state=seed)
scores=cross_val_score(random_forest_model,x_train_data_transform,y_train_data,cv=k_fold)
scores

array([0.72, 0.72, 0.74, 0.62, 0.78, 0.84, 0.82, 0.74, 0.72, 0.74])

In [0]:
#Calculate Mean score

In [51]:
scores.mean()

0.744

In [0]:
# Calculate score standard deviation using std()

In [52]:
scores.std()

0.057827329179203836

# Q8 Print the confusion matrix( 1 Marks)

In [53]:
confusion_matrix(y_test,y_predicted)

array([[96,  6],
       [32, 16]], dtype=int64)

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [55]:
from sklearn.metrics import recall_score,precision_score

In [56]:
print('recall {}'.format(recall_score(y_test,y_predicted)))
print('precision {}'.format(precision_score(y_test,y_predicted)))

recall 0.3333333333333333
precision 0.7272727272727273


# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [0]:
#Hint: Use roc_curve

In [57]:
from sklearn.metrics import roc_curve
roc_curve(y_test,y_predicted)

(array([0.        , 0.05882353, 1.        ]),
 array([0.        , 0.33333333, 1.        ]),
 array([2, 1, 0], dtype=int64))

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

In [58]:
from sklearn.metrics import roc_auc_score

In [59]:
roc_auc_score(y_test,y_predicted)

0.6372549019607843

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [60]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [64]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(x_train, y_train)
    random_forest_model.fit(X_, y_)
    y_pred = random_forest_model.predict(x_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

In [65]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  0.732
Standard deviation:  0.016812693617224657
